LIST=LIB
EARLY_DIRS=c drvr m compat qnx socket tar z bzip2 lzma expat cache gf strm jpeg png tiff login power shm_lock kalman misc termcap bmetrics mmutil pps spi-master screen khronos certicom_toolkits slog2 libiconv fastmemcpy
LATE_DIRS=lua fontconfig ids_native_sdk io-pkt radio playready squrl gri mesa imaging pkgdiff package audioman mmedia camapi md mmplaylist avp_api bps bbid_native_sdk adc audio_config glib gmime tts_engine VoiceServices wmpinfo mm-copy usb-1.0 mm-browse aoa OpenMAXAL
include recurse.mk
