# This is an automatically generated record.
# The area between QNX Internal Start and QNX Internal End is controlled by
# the QNX IDE properties.


ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

include $(MKFILES_ROOT)/qmacros.mk
NAME=mdriver-info
#===== USEFILE - the file containing the usage message for the application.
USEFILE=$(PROJECT_ROOT)/mdriver-info.c


EXTRA_SILENT_VARIANTS+=$(SECTION)

define PINFO
PINFO DESCRIPTION=mdriver-info
endef

#The following line must appear because it causes bsp_tag.sh to insert
#INSTALL_ROOT_nto defines after it and hence before qtargets.
#Those defines must appear before qtargets to ensure that the vpath includes
#the staging area created by bsp_validate.
-include $(PROJECT_ROOT)/roots.mk


#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

