ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

include $(MKFILES_ROOT)/qmacros.mk
-include $(PROJECT_ROOT)/roots.mk

define PINFO
PINFO DESCRIPTION=i.MX6X PMIC Driver
endef

NAME := pmic-pmpf0100
USEFILE = $(PROJECT_ROOT)/pmic-pmpf0100.use
INSTALLDIR = sbin


#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

