
EXTRA_SRCVPATH += $(PROJECT_ROOT)/../codecs/cs42448/
EXTRA_INCVPATH += $(PRODUCT_ROOT)/../codecs/cs42448/

SDMA_LIB=dma-sdma-imx6x
LIBS_mxesai += $(SDMA_LIB)
LIBS_mxesai += drvr

include ../../../../common.mk


